//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CattleProduction
    {
        public int IdProduction { get; set; }
        public int IdCattle { get; set; }
        public System.DateTime Dateprod { get; set; }
        public string hourprod { get; set; }
        public decimal quantity { get; set; }
    
        public virtual Cattle Cattle { get; set; }
    }
}
