//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cattle
    {
        public Cattle()
        {
            this.CattleProductions = new HashSet<CattleProduction>();
            this.DiseasesHistories = new HashSet<DiseasesHistory>();
            this.Gestations = new HashSet<Gestation>();
        }
    
        public int IdCattle { get; set; }
        public string CodeCattle { get; set; }
        public int IdHerd { get; set; }
        public int IdState { get; set; }
        public bool Active { get; set; }
        public System.DateTime DateBirth { get; set; }
        public Nullable<int> MalParent { get; set; }
        public Nullable<int> FemaleParent { get; set; }
        public string Sex { get; set; }
    
        public virtual ICollection<CattleProduction> CattleProductions { get; set; }
        public virtual Herd Herd { get; set; }
        public virtual ICollection<DiseasesHistory> DiseasesHistories { get; set; }
        public virtual ICollection<Gestation> Gestations { get; set; }
        public virtual HealthState HealthState { get; set; }
    }
}
