//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diet
    {
        public Diet()
        {
            this.CattleTypes = new HashSet<CattleType>();
            this.Foods = new HashSet<Food>();
        }
    
        public int IdDiet { get; set; }
        public int IdSeason { get; set; }
        public string Label { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual ICollection<CattleType> CattleTypes { get; set; }
        public virtual ICollection<Food> Foods { get; set; }
    }
}
