//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseasesHistory
    {
        public int IdDiseasesHistory { get; set; }
        public int IdTreatment { get; set; }
        public int IdDisease { get; set; }
        public int IdCattle { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool VeterinaryVisit { get; set; }
    
        public virtual Cattle Cattle { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual MedicalTreatment MedicalTreatment { get; set; }
    }
}
