//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.Meals = new HashSet<Meal>();
            this.Diets = new HashSet<Diet>();
        }
    
        public int IdFood { get; set; }
        public decimal TotQuantity { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual ICollection<Diet> Diets { get; set; }
    }
}
