//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herd
    {
        public Herd()
        {
            this.Cattles = new HashSet<Cattle>();
            this.Meals = new HashSet<Meal>();
        }
    
        public int IdHerd { get; set; }
        public int IdCattleType { get; set; }
        public int MaxAnimals { get; set; }
        public bool Active { get; set; }
        public string Label { get; set; }
        public int AvailablePlaces { get; set; }
    
        public virtual ICollection<Cattle> Cattles { get; set; }
        public virtual CattleType CattleType { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
