//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DairyFarmEntities : DbContext
    {
        public DairyFarmEntities()
            : base("name=DairyFarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CattleProduction> CattleProductions { get; set; }
        public virtual DbSet<Cattle> Cattles { get; set; }
        public virtual DbSet<CattleType> CattleTypes { get; set; }
        public virtual DbSet<Diet> Diets { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<DiseasesHistory> DiseasesHistories { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Gestation> Gestations { get; set; }
        public virtual DbSet<HealthState> HealthStates { get; set; }
        public virtual DbSet<Herd> Herds { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MedicalTreatment> MedicalTreatments { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
    }
}
