//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DairyFarm.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int IdMeal { get; set; }
        public int IdFood { get; set; }
        public int IdHerd { get; set; }
        public System.DateTime DateMeal { get; set; }
        public Nullable<System.TimeSpan> HourMeal { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Herd Herd { get; set; }
    }
}
